name: Test Gh Workflows
on: [push]
jobs:
  TestJob1:
    runs-on: ubuntu-latest
    steps:
      - name: Run 1st Hello World
        run: echo "Hello World!"
      - run: echo "Hello World2"
      - run: echo "Hello WOrld3"
  CheckoutRepo:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      - run: echo "Cloned ${{ github.repository }} successfully!!!
